# Generated by Django 2.2.6 on 2019-10-04 08:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietario', models.CharField(blank=True, max_length=255, null=True, verbose_name='proprietário')),
                ('orgao', models.CharField(blank=True, max_length=255, null=True, verbose_name='órgão responsável')),
                ('data_perfuracao', models.DateField(blank=True, null=True, verbose_name='data de perfuração')),
                ('profundidade', models.FloatField(blank=True, null=True, verbose_name='profundidade (m)')),
                ('q_m3h', models.FloatField(blank=True, null=True, verbose_name='vazão m3/h')),
                ('equipamento', models.CharField(blank=True, max_length=255, null=True, verbose_name='equipamento')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='geom')),
            ],
        ),
    ]
