# Generated by Django 4.1.13 on 2024-11-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poco', '0002_alter_poco_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poco',
            options={'verbose_name': 'Poço', 'verbose_name_plural': 'Poços'},
        ),
    ]
