# Generated by Django 4.1.13 on 2024-11-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
