# Generated by Django 4.1.13 on 2024-11-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipio', '0002_alter_municipio_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name': 'Município', 'verbose_name_plural': 'Municípios'},
        ),
    ]
